# 이 파일은 Cloud Build가 수행할 작업의 순서와 설정을 정의합니다.
# 각 단계(step)는 순차적으로 실행됩니다.

steps:
# --- 1단계: Docker 이미지 빌드 및 Artifact Registry에 푸시 ---
# 'gcr.io/cloud-builders/docker'는 GCP에서 제공하는 공식 Docker 빌드 도구입니다.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    # 빌드된 이미지에 태그를 지정합니다. (리전을 us-central1으로 변경)
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/star-compare-repo/backend:$COMMIT_SHA'
    # 빌드 컨텍스트는 현재 디렉토리('.')입니다.
    - '.'
  id: 'Build Docker Image'

# --- 2단계: 데이터베이스 마이그레이션 실행 ---
# 'gcr.io/google-appengine/exec-wrapper'는 Cloud SQL 프록시를 통해
# 컨테이너가 데이터베이스에 안전하게 연결하고 명령을 실행할 수 있도록 도와줍니다.
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
    # '-i': 방금 빌드한 Docker 이미지를 지정합니다. (리전을 us-central1으로 변경)
    - '-i'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/star-compare-repo/backend:$COMMIT_SHA'
    # '-s': 연결할 Cloud SQL 인스턴스를 지정합니다.
    # ${_INSTANCE_CONNECTION_NAME}은 트리거의 대체 변수에서 가져옵니다.
    - '-s'
    - '${_INSTANCE_CONNECTION_NAME}'
    # '--': exec-wrapper에 전달하는 인수가 끝나고, 컨테이너 내부에서 실행할 실제 명령어가 시작됨을 알립니다.
    - '--'
    - 'python'
    - 'manage.py'
    - 'migrate'
  id: 'Run Database Migrations'

# --- 3단계: Cloud Run에 새 버전 배포 ---
# 'gcr.io/google-cloud-sdk/gcloud'는 gcloud CLI 명령어를 실행하는 도구입니다.
- name: 'gcr.io/google-cloud-sdk/gcloud'
  args:
    - 'run'
    - 'deploy'
    # 배포할 Cloud Run 서비스의 이름을 지정합니다.
    - 'star-compare-service'
    # 배포할 이미지의 전체 경로를 지정합니다. (리전을 us-central1으로 변경)
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/star-compare-repo/backend:$COMMIT_SHA'
    # 서비스가 실행될 리전을 지정합니다. (리전을 us-central1으로 변경)
    - '--region=us-central1'
    # 플랫폼은 'managed'로 설정합니다.
    - '--platform=managed'
    # Cloud SQL 인스턴스와의 안전한 연결을 설정합니다.
    - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
    # Secret Manager에 저장된 보안 비밀들을 환경 변수로 주입합니다.
    # 형식: '--set-secrets=[환경변수명]=[보안비밀명]:[버전]'
    - '--set-secrets=SECRET_KEY=DJANGO_SECRET_KEY:latest,DB_NAME=DB_NAME:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest'
  id: 'Deploy to Cloud Run'

# 빌드가 완료된 후 Artifact Registry에 저장될 이미지 목록입니다.
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/star-compare-repo/backend:$COMMIT_SHA'

# 로깅 옵션: 빌드 로그를 별도의 버킷이 아닌 Cloud Logging에만 저장합니다.
options:
  logging: CLOUD_LOGGING_ONLY
