# 이 파일은 오직 Secret Manager 접근 권한을 테스트하기 위한 최소한의 빌드 파일입니다.
steps:
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  # 테스트할 비밀을 단 하나만 지정합니다.
  secretEnv: ['SECRET_KEY']
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Starting secret access test..."
      if [ -z "$SECRET_KEY" ]; then
        echo "TEST FAILED: SECRET_KEY environment variable is empty or not set."
        exit 1
      else
        echo "TEST SUCCEEDED: SECRET_KEY was successfully accessed."
        # 실제 키 값을 노출하지 않고, 첫 5자리만 출력하여 확인합니다.
        echo "First 5 chars of the key: ${SECRET_KEY:0:5}..."
      fi