# Generated by Django 5.2.3 on 2025-06-21 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.IntegerField(help_text='업종 코드 (예: 한식 2001)', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='업종 이름 (예: 한식)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.IntegerField(help_text='지역 코드 (예: 서울 100)', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='지역 이름 (예: 서울)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('code', models.IntegerField(help_text='세부 지역 코드 (예: 강남 1001)', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='세부 지역 이름 (예: 강남)', max_length=50)),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='favorites.region')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='favorites.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='favorites.region')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='favorites.subregion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
